In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
# import datasets
X = pd.read_csv("dataset_normalised.csv")
y = pd.read_csv("labnf.csv")

# numberical column that are needed for training
numeric_columns=['Shares (Basic)',
       'Shares (Diluted)', 'Cash, Cash Equivalents & Short Term Investments',
       'Accounts & Notes Receivable', 'Inventories', 'Total Current Assets',
       'Property, Plant & Equipment, Net',
       'Long Term Investments & Receivables', 'Other Long Term Assets',
       'Total Noncurrent Assets', 'Total Assets', 'Payables & Accruals',
       'Short Term Debt', 'Total Current Liabilities', 'Long Term Debt',
       'Total Noncurrent Liabilities', 'Total Liabilities',
       'Share Capital & Additional Paid-In Capital', 'Treasury Stock',
       'Retained Earnings', 'Total Equity', 'Total Liabilities & Equity',
       'Price_Present']
X = X[numeric_columns]
X.head()


Shares (Basic)  Shares (Diluted)  \
0        0.013189          0.013262   
1        0.013075          0.013413   
2        0.013189          0.013376   
3        0.013189          0.013376   
4        0.013227          0.013451   

   Cash, Cash Equivalents & Short Term Investments  \
0                                         0.016228   
1                                         0.018553   
2                                         0.018476   
3                                         0.020836   
4                                         0.021719   

   Accounts & Notes Receivable  Inventories  Total Current Assets  \
0                     0.002050     0.009389              0.011391   
1                     0.002255     0.009771              0.012253   
2                     0.002216     0.010876              0.009133   
3                     0.002382     0.011640              0.010122   
4                     0.002380     0.012241              0.010374   

   Property, Plant & Equipment, Net  Long Term Investments & Receivables  \
0                          0.018365                             0.000530   
1                          0.018454                             0.000553   
2                          0.018462                             0.000522   
3                          0.018547                             0.000479   
4                          0.018531                             0.000475   

   Other Long Term Assets  Total Noncurrent Assets  ...  \
0                0.006310                 0.012129  ...   
1                0.006675                 0.012404  ...   
2                0.006469                 0.012266  ...   
3                0.006733                 0.012448  ...   
4                0.006684                 0.012409  ...   

   Total Current Liabilities  Long Term Debt  Total Noncurrent Liabilities  \
0                   0.009165        0.006773                      0.015508   
1                   0.009686        0.006809                      0.015518   
2                   0.004417        0.006664                      0.015309   
3                   0.005002        0.006681                      0.014763   
4                   0.004728        0.006748                      0.014634   

   Total Liabilities  Share Capital & Additional Paid-In Capital  \
0           0.012695                                    0.055579   
1           0.012950                                    0.055888   
2           0.010308                                    0.056873   
3           0.010283                                    0.057378   
4           0.010079                                    0.058060   

   Treasury Stock  Retained Earnings  Total Equity  \
0        0.965186           0.190487      0.066599   
1        0.964960           0.191052      0.067596   
2        0.963789           0.191426      0.067837   
3        0.963789           0.191812      0.069293   
4        0.962956           0.192451      0.069853   

   Total Liabilities & Equity  Price_Present  
0                    0.011541   3.266000e-07  
1                    0.012297   4.062000e-07  
2                    0.010202   4.604000e-07  
3                    0.010969   4.769000e-07  
4                    0.011101   3.568000e-07  

[5 rows x 23 columns]

In [3]:
y = y["Label"]
y.head()

0    0
1    0
2    0
3    1
4    2
Name: Label, dtype: int64

In [5]:
y.value_counts()

0    27096
1    20541
2    11191
Name: Label, dtype: int64

# Classification Model
1. Naive Bayes
1. Logistic Regression
1. Support Vector Classifier
1. Random Forest
1. Decision Tree
1. Nearest Neighbour
1. Gaussian Process*
1. Linear Discriminant Analysis* (LDA)
1. Quadratic Discriminant Analysis* (LDA)

## Model Selection

1. K fold cross
1. Grid Search
1. precision, recall, f1-score and confusion matrix

In [56]:
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV

## 1.Naive Bayes

In [73]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()

kf = KFold(n_splits=5,shuffle=True)

scores = []
cm_holder = []

for train_index,test_index in kf.split(X):
    X_train,X_test = X.iloc[train_index],X.iloc[test_index]
    y_train,y_test = y.iloc[train_index],y.iloc[test_index]
        
    clf.fit(X_train,y_train)
    
    train_score = clf.score(X_train,y_train)
    test_score = clf.score(X_test,y_test)
    
    scores.append((train_score,test_score))
    
    cm_holder.append(confusion_matrix(y_test,clf.predict(X_test)))
    
print("Accuracy :\tTrain\t\t\tTest\n")
train_avg = 0
test_avg = 0
for i in range(len(scores)):
    train_avg += scores[i][0]
    test_avg += scores[i][1]
    print("Split {}:\t{}%\t{}%".format(i,scores[i][0]*100,scores[i][1]*100))

print("\nMean :\t\t{}%\t{}%".format(train_avg/len(scores)*100,test_avg/len(scores)*100))

final_cm = np.zeros((3,3))
for cm in cm_holder:
    final_cm += cm

# print averaged confusion matrix

print("\nConfusion Matrix:\n\n",final_cm/len(cm_holder))




Accuracy :	Train			Test

Split 0:	45.29131783604607%	46.60037395886453%
Split 1:	45.52930177213038%	45.09603943566208%
Split 2:	45.66104287960563%	45.147033826279106%
Split 3:	45.64519898858976%	45.33786655333616%
Split 4:	45.50921105751865%	45.54186145346366%

Mean :		45.527214506778094%	45.544635045521105%

Confusion Matrix:

 [[5.2530e+03 6.0000e-01 1.6560e+02]
 [4.0008e+03 3.0000e+00 1.0440e+02]
 [2.1354e+03 2.0000e-01 1.0260e+02]]
